apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountservice
  template:
    metadata:
      labels:
        app: accountservice
    spec:
      containers:
        - name: accountservice
          image: 182506/accountservice.microservice:latest