apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: accountservice
    spec:
      containers:
        - name: accountservice
          image: 182506/accountservice.microservice:latest
        
          resources:
            requests:
              memory: "50Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "2000"