name: AccountService.Microservice CI/CD

#Controls when the workflow will run
on:
#Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, Development]
  pull_request:
    branches: [main]
    
#Allows you to run this workflow manually from the actions tab
workflow_dispatch:

env:
  PATH_TO_SLN: './Backend/AccountService/AccountService.Microservice.csproj'
  PATH_TO_DOCKERFILE: './Backend/AccountService/Dockerfile'
  DOCKER_IMAGE_NAME: 'accountservice.microservice:latest'
  DOCKER_REPO_NAME: 182506/accountservice.microservice
  
  # A workflow run is made up of one or more hobs that can run sequentially or parallel
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build . --file $PATH_TO_DOCKERFILE --tag $DOCKER_IMAGE_NAME
    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACCTOKEN }}
    - name: tag image
      run: docker tag $DOCKER_IMAGE_NAME $DOCKER_REPO_NAME
    - name: push image
      run: docker push $DOCKER_REPO:latest
